#:schema node_modules/wrangler/config-schema.json
name = "astro-cloudflare-d1"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "astro-cloudflare-d1"
database_id = "b5710955-d3c2-49dc-8dc3-01b0943df8d9"
preview_database_id = "DB"
